### ISSUE TITLE
[Feature Request] Allow configuring auth scopes with Docker env variable

### ISSUE THREAD

**Issue by ddavidyuk** [temporalio/ui-server#210]
### Is your feature request related to a problem? Please describe.

We want to configure OpenID Connect auth for Temporal UI and also enable default Authorizer / ClaimMapper in Temporal Server. The default claim mapper uses the "permissions" claim to extract namespace-level roles. So for OpenID we would need to add a "permissions" claim to the user's access token with e.g. "system:write" or "system:read" values.
The IDP we are using links claims to scopes, so we'd have to link the "permissions" claim to the "openid" scope. The openid scope is a global scope used by lots of other clients (not related to Temporal), so the "permissions" claim would be added to all these access tokens that don't really need it.
Instead we would like to be able to specify an additional custom scope via env variable 

### Describe the solution you'd like
Additional `TEMPORAL_UI_OAUTH_SCOPE` env variable that lets you specify an additional scope for OpenID Connect auth
```yaml
auth:
  enabled: {{ default .Env.TEMPORAL_AUTH_ENABLED "false" }}
  providers:
  - label: {{ default .Env.TEMPORAL_AUTH_LABEL "sso" }}
    type: {{ default .Env.TEMPORAL_AUTH_TYPE "oidc" }}
    providerUrl: {{ .Env.TEMPORAL_AUTH_PROVIDER_URL }}
    issuerUrl: {{ default .Env.TEMPORAL_AUTH_ISSUER_URL "" }}
    clientId: {{ .Env.TEMPORAL_AUTH_CLIENT_ID }}
    clientSecret: {{ .Env.TEMPORAL_AUTH_CLIENT_SECRET }}
    callbackUrl: {{ .Env.TEMPORAL_AUTH_CALLBACK_URL }}
    scopes:
      - openid
      - profile
      - email
      - {{ .Env.TEMPORAL_AUTH_SCOPE "temporal_ui" }} // <------ NEW
```
